### ISSUE TITLE
Omnipay 2.0 support

### ISSUE THREAD

**Issue by sudiptpa** [ignited/omnipay-zippay#1]
Hey !

I was looking for the Zip Pay Integration for my old Laravel v4.2 project, but i cannot upgrade it to Lv5 now. This package seems to be only have support for Omnipay v3.0 version. So having problem installing it on lower version of my project.

I want to submit a PR for Omnipay v2.0 support and i have a short deadline. I wanted to know how actively the package is being maintained, and would love to receive PR, review, merge, tag a new release?

**Comment by dcon138** [comment]
Hi @sudiptpa ,

We don't actively develop this package, and as such don't have plan to implement support for Omnipay v2.0.

However, if you want to submit a PR to implement this functionality, we'll be happy to have a look at it.

Thanks!
